using MainGUI;
using UnityEngine;

namespace Progression
{
    public class TutorialView : MonoBehaviour
    {
        [SerializeField] private GameObject _blocker1;
        [SerializeField] private GameObject _blocker2;
        [SerializeField] private GameObject _blocker3;
        [SerializeField] private GameObject _blocker4;
        [SerializeField] private GameObject _blocker5;
        [SerializeField] private GameObject _tutorialAskPanel;
        [SerializeField] private ButtonView _tutorialStartButton;
        [SerializeField] private ButtonView _tutorialSkipButton;
        [SerializeField] private GameObject _tutorialStartedPanel;
        [SerializeField] private ButtonView _tutorialContinueButton;
        [SerializeField] private GameObject _clientTutorialPanel;
        [SerializeField] private GameObject _dialogueTutorialPanel;
        [SerializeField] private GameObject _orderAcceptedTutorialPanel;
        [SerializeField] private GameObject _ordersListTutorialPanel;
        [SerializeField] private GameObject _forgingStartedTutorialPanel;
        [SerializeField] private GameObject _forgingFirstHitTutorialPanel;
        [SerializeField] private GameObject _forgingChangeStageTutorialPanel;
        [SerializeField] private GameObject _resultScreenTutorialPanel;
        [SerializeField] private GameObject _orderFinishedTutorialPanel;
        [SerializeField] private GameObject _orderSubmitOrderTutorialPanel;
        [SerializeField] private GameObject _fristMoneyTutorialPanel;
        [SerializeField] private GameObject _firstMoney2TutorialPanel;
        [SerializeField] private GameObject _shopTutorialPanel;
        [SerializeField] private GameObject _shop2TutorialPanel;
        [SerializeField] private GameObject _shop3TutorialPanel;
        [SerializeField] private ButtonView _shopTutorialContinueButton;
        [SerializeField] private GameObject _moneyAccumulatedTutorialPanel;
        [SerializeField] private GameObject _upradeBoughtTutorialPanel;
        [SerializeField] private GameObject _materialUnavaliableTutorialPanel;
        [SerializeField] private GameObject _materialsTutorialPanel;
        [SerializeField] private GameObject _materials2TutorialPanel;
        [SerializeField] private GameObject _materialChangingTutorialPanel;
        [SerializeField] private GameObject _orderInfoTutorialPanel;
        [SerializeField] private GameObject _orderMaterialsTutorialPanel;
        [SerializeField] private ButtonView _basicTutorialEndButton;
        [SerializeField] private GameObject _additionalStageAddedTutorialPanel;
        [SerializeField] private GameObject _smeltingStartedTutorialPanel;
        [SerializeField] private ButtonView _smeltingContinueButton;
        [SerializeField] private GameObject _smeltingNearTriggerTutorialPanel;
        [SerializeField] private GameObject _smeltingGoodHitTutorialPanel;
        [SerializeField] private ButtonView _smeltingContinueButton2;
        [SerializeField] private GameObject _forgingAfterSmeltingTutorialPanel;
        [SerializeField] private GameObject _tradeStartTutorialPanel;
        [SerializeField] private GameObject _tradeScreenTutorialPanel;
        [SerializeField] private ButtonView _tradeScreenContinueButton;
        [SerializeField] private GameObject _tradeGreenZoneTutorialPanel;
        [SerializeField] private ButtonView _tradeScreenContinueButton2;
        [SerializeField] private GameObject _tradeFinishTutorialPanel;
        [SerializeField] private GameObject _hardeningStartTutorialPanel;
        [SerializeField] private ButtonView _hardeningContinueButton;
        [SerializeField] private GameObject _hardeningGoodHitTutorialPanel;
        [SerializeField] private ButtonView _hardeningContinueButton2;
        [SerializeField] private GameObject _sharpeningStartTutorialPanel;
        [SerializeField] private ButtonView _sharpeningContinueButton;
        [SerializeField] private GameObject _sharpeningGoodHitTutorialPanel;
        [SerializeField] private GameObject _sharpeningBadHitTutorialPanel;
        [SerializeField] private ButtonView _sharpeningContinue2Button;
        [SerializeField] private ButtonView _sharpeningContinue3Button;
        
        
        

        public GameObject Blocker1 => _blocker1;
        public GameObject Blocker2 => _blocker2;
        public GameObject Blocker3 => _blocker3;
        public GameObject Blocker4 => _blocker4;
        public GameObject Blocker5 => _blocker5;
        public GameObject TutorialAskPanel => _tutorialAskPanel;
        public ButtonView TutorialStartButton => _tutorialStartButton;
        public ButtonView TutorialSkipButton => _tutorialSkipButton;
        public GameObject TutorialStartedPanel => _tutorialStartedPanel;
        public ButtonView TutorialContinueButton => _tutorialContinueButton;
        public GameObject ClientTutorialPanel => _clientTutorialPanel;
        public GameObject DialogueTutorialPanel => _dialogueTutorialPanel;
        public GameObject OrderAcceptedTutorialPanel => _orderAcceptedTutorialPanel;
        public GameObject OrdersListTutorialPanel => _ordersListTutorialPanel;
        public GameObject ForgingStartedTutorialPanel => _forgingStartedTutorialPanel;
        public GameObject ForgingFirstHitTutorialPanel => _forgingFirstHitTutorialPanel;
        public GameObject ForgingChangeStageTutorialPanel => _forgingChangeStageTutorialPanel;
        public GameObject ResultScreenTutorialPanel => _resultScreenTutorialPanel;
        public GameObject OrderFinishedTutorialPanel => _orderFinishedTutorialPanel;
        public GameObject OrderSubmitOrderTutorialPanel => _orderSubmitOrderTutorialPanel;
        public GameObject FristMoneyTutorialPanel => _fristMoneyTutorialPanel;
        public GameObject FirstMoney2TutorialPanel => _firstMoney2TutorialPanel;
        public GameObject ShopTutorialPanel => _shopTutorialPanel;
        public GameObject Shop2TutorialPanel => _shop2TutorialPanel;
        public GameObject Shop3TutorialPanel => _shop3TutorialPanel;
        public ButtonView ShopTutorialContinueButton => _shopTutorialContinueButton;
        public GameObject MoneyAccumulatedTutorialPanel => _moneyAccumulatedTutorialPanel;
        public GameObject UpgradeBoughtTutorialPanel => _upradeBoughtTutorialPanel;
        public GameObject MaterialUnavaliableTutorialPanel => _materialUnavaliableTutorialPanel;
        public GameObject MaterialsTutorialPanel => _materialsTutorialPanel;
        public GameObject Materials2TutorialPanel => _materials2TutorialPanel;
        public GameObject MaterialChangingTutorialPanel => _materialChangingTutorialPanel;
        public GameObject OrderInfoTutorialPanel => _orderInfoTutorialPanel;
        public GameObject OrderMaterialsTutorialPanel => _orderMaterialsTutorialPanel;
        public ButtonView BasicTutorialEndButton => _basicTutorialEndButton;
        public GameObject AdditionalStageAddedTutorialPanel => _additionalStageAddedTutorialPanel;
        public GameObject SmeltingStartedTutorialPanel => _smeltingStartedTutorialPanel;
        public ButtonView SmeltingContinueButton => _smeltingContinueButton;
        public GameObject SmeltingNearTriggerTutorialPanel => _smeltingNearTriggerTutorialPanel;
        public GameObject SmeltingGoodHitTutorialPanel => _smeltingGoodHitTutorialPanel;
        public ButtonView SmeltingContinueButton2 => _smeltingContinueButton2;
        public GameObject ForgingAfterSmeltingTutorialPanel => _forgingAfterSmeltingTutorialPanel;
        public GameObject TradeStartTutorialPanel => _tradeStartTutorialPanel;
        public GameObject TradeScreenTutorialPanel => _tradeScreenTutorialPanel;
        public ButtonView TradeScreenContinueButton => _tradeScreenContinueButton;
        public GameObject TradeGreenZoneTutorialPanel => _tradeGreenZoneTutorialPanel;
        public ButtonView TradeScreenContinueButton2 => _tradeScreenContinueButton2;
        public GameObject TradeFinishTutorialPanel => _tradeFinishTutorialPanel;
        public GameObject HardeningStartTutorialPanel => _hardeningStartTutorialPanel;
        public ButtonView HardeningContinueButton => _hardeningContinueButton;
        public GameObject HardeningGoodHitTutorialPanel => _hardeningGoodHitTutorialPanel;
        public ButtonView HardeningContinueButton2 => _hardeningContinueButton2;
        public GameObject SharpeningStartTutorialPanel => _sharpeningStartTutorialPanel;
        public ButtonView SharpeningContinueButton => _sharpeningContinueButton;
        public GameObject SharpeningGoodHitTutorialPanel => _sharpeningGoodHitTutorialPanel;
        public GameObject SharpeningBadHitTutorialPanel => _sharpeningBadHitTutorialPanel;
        public ButtonView SharpeningContinue2Button => _sharpeningContinue2Button;
        public ButtonView SharpeningContinue3Button => _sharpeningContinue3Button;
    }
}